{:ok, adm1} = Admin.start_link("admin")
{:ok, a1} = Agency.start_link("ag1")
{:ok, a2} = Agency.start_link("ag2")
{:ok, _p1} = Provider.start_link("prov1", ["satellite", "personal"])
{:ok, _p2} = Provider.start_link("prov2", ["satellite", "load"])

GenServer.cast(a1, {:order, "load"})
GenServer.cast(a2, {:order, "load"})
GenServer.cast(a1, {:order, "satellite"})
GenServer.cast(a2, {:order, "personal"})
GenServer.cast(a1, {:order, "personal"})
GenServer.cast(a2, {:order, "satellite"})
GenServer.cast(a2, {:order, "satellite"})
GenServer.cast(a1, {:order, "satellite"})
GenServer.cast(a2, {:order, "satellite"})
GenServer.cast(adm1, {:to_provider, "elo providerzy"})
GenServer.cast(adm1, {:to_agency, "elo agencje"})
GenServer.cast(adm1, {:to_all, "elo wszyscy"})
